### ISSUE TITLE
Please provide these submission hash for libigl 、cinolib 

### ISSUE THREAD

**Issue by XLionXL** [muntonialessandro/HeightFieldDecomposition#1]

**Comment by alemuntoni** [comment]
You're right, but I just don't have time to maintain and keep up to date all my old projects, and I developed this one when I had no clue on how to use git submodules and cmake.

Anyway, did you tried the 2018 tags/commits? 
e.g. libigl does have its first tag on 2018 ([this one](https://github.com/libigl/libigl/releases/tag/v1.3.1)), and for cinolib, for which no tags are available, you could try a 2018 commit (like [this one](https://github.com/mlivesu/cinolib/tree/5e3d3d24d7e5d83d7bb210943f1620bcc610724d)). I am pretty sure that these versions work.

**Comment by XLionXL** [comment]
I'm very sorry, I just saw your reply and I am very grateful for your work. It has been very useful to me, and I am currently trying to submit in 2018

**Comment by XLionXL** [comment]
![image](https://github.com/alemuntoni/HeightFieldDecomposition/assets/111164867/0e45089a-348f-44bf-b176-15a862f969df)
![image](https://github.com/alemuntoni/HeightFieldDecomposition/assets/111164867/751c2720-0beb-4321-9a8c-418c4c46f603)
![image](https://github.com/alemuntoni/HeightFieldDecomposition/assets/111164867/f46d1765-70b4-48b7-81e2-1f1de8bda5ba)

I used the libigl source code package you provided, but encountered an error during compilation. I couldn't find ply. h in the igl path. I searched the source code, but it only showed removing the hash of ply. h

**Comment by XLionXL** [comment]
> ![image](https://private-user-images.githubusercontent.com/111164867/305697770-0e45089a-348f-44bf-b176-15a862f969df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDY3NjQsIm5iZiI6MTcwODMwNjQ2NCwicGF0aCI6Ii8xMTExNjQ4NjcvMzA1Njk3NzcwLTBlNDUwODlhLTM0OGYtNDRiZi1iMTc2LTE1YTg2MmY5NjlkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwMTM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2NjZGIyY2VhZWVlNTBlNjE2YjRhN2U4MWMzNjcxZWU0NjVjMGJkMGViODc1ZDZhMTc3NjFlOWUwMzZhYjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OcSlx_oBa0vIXc_mvoWh-U4cHFQcg3FSJQkTWVhCpRE) ![image](https://private-user-images.githubusercontent.com/111164867/305697851-751c2720-0beb-4321-9a8c-418c4c46f603.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDY3NjQsIm5iZiI6MTcwODMwNjQ2NCwicGF0aCI6Ii8xMTExNjQ4NjcvMzA1Njk3ODUxLTc1MWMyNzIwLTBiZWItNDMyMS05YThjLTQxOGM0YzQ2ZjYwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwMTM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDdkYzhmNDdjYTFlMzY0MDViNmU5ZDNhNzVmMmI1NjhiMmFhMjM5ZjQ1YjRjNjQyMDY2ODAwMjJjNDU4ODU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._zlXzwG7WV_kTL4h-DZbcC8TNOJt0kyvceU6PDp1shc) ![image](https://private-user-images.githubusercontent.com/111164867/305697994-f46d1765-70b4-48b7-81e2-1f1de8bda5ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDY3NjQsIm5iZiI6MTcwODMwNjQ2NCwicGF0aCI6Ii8xMTExNjQ4NjcvMzA1Njk3OTk0LWY0NmQxNzY1LTcwYjQtNDhiNy04MWUyLTFmMWRlOGJkYTViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwMTM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDU4ODIwYmZjNzBjOTkwYTc3MTJjMDdkYzc1YzdlOTlhYzQ0NjYxZTVlOTQ1ZWJmZDE2MWM5MDcyYzE2Nzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sYDo6QDLnL1VuYiXZNov0hupPVxujJCNP5sVwjE3fYc)
> 
> I used the libigl source code package you provided, but encountered an error during compilation. I couldn't find ply. h in the igl path. I searched the source code, but it only showed removing the hash of ply. h
I solved the problem of not being able to find ply. h by using libigl-1.3.3, but some new problems have emerged:
![image](https://github.com/alemuntoni/HeightFieldDecomposition/assets/111164867/1f1fe11e-2bc1-4dcc-ae58-b6b8166c83bd)

![image](https://github.com/alemuntoni/HeightFieldDecomposition/assets/111164867/ea477c2b-a341-446c-a97d-f0648902a93e)
![image](https://github.com/alemuntoni/HeightFieldDecomposition/assets/111164867/e76ce20f-dced-418f-9acc-adfcf00b6010)

![image](https://github.com/alemuntoni/HeightFieldDecomposition/assets/111164867/4da392fd-e54e-4a5d-9c36-a27681f1a65e)

**Comment by XLionXL** [comment]
![image](https://github.com/alemuntoni/HeightFieldDecomposition/assets/111164867/7bfdc2d5-1ae1-49ef-9c7d-10a305940134)
I cannot find the definition of this function throughout the entire project: deleteBoxesNonOptimial()
